import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { MODULES, type EnvSpec } from '../src/modules.js';
import { scanEnvKeys } from './env-keys.js';

/**
 * Writes .env.example from the module env specs in src/modules.ts.
 *
 *   npm run env:example            write .env.example
 *   npm run env:example -- --check exit 1 if the file is stale or a key the
 *                                  code reads is not documented by any module
 *
 * Do not hand-edit .env.example; edit the module's `env` list and re-run.
 */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function comment(text: string): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '#';
  for (const w of words) {
    if ((line + ' ' + w).length > 80 && line !== '#') { lines.push(line); line = '#'; }
    line += ' ' + w;
  }
  lines.push(line);
  return lines;
}

function entry(e: EnvSpec, note = ''): string[] {
  return [...comment(`${e.description}${note}`), `${e.key}=${e.example ?? ''}`];
}

export function renderEnvExample(): string {
  const out: string[] = [];
  const written = new Set<string>();
  out.push('# ─────────────────────────────────────────────────────────────────────────────');
  out.push('# GENERATED by `npm run env:example` from src/modules.ts. Do not edit by hand.');
  out.push('# Copy to .env (cp .env.example .env) or let `npm run onboard` fill it in.');
  out.push('# Then run `npm run doctor -- --setup` to see what is still missing.');
  out.push('#');
  out.push('# Features are switched on and off in config/profile.json:');
  out.push('#   "modules": { "email": true, "checkins": true }');
  out.push('# Settings for a feature that is off are simply ignored.');
  out.push('# ─────────────────────────────────────────────────────────────────────────────');
  out.push('');
  out.push('# ── Required ─────────────────────────────────────────────────────────────────');
  out.push('');
  const core = MODULES.find((m) => m.alwaysOn)!;
  for (const e of core.env.filter((x) => x.required)) {
    out.push(...entry(e), '');
    written.add(e.key);
  }

  for (const m of MODULES) {
    const rest = m.env;
    const title = `${m.title} (${m.id}) — ${m.alwaysOn ? 'always on' : m.defaultEnabled ? 'on by default' : 'off by default'}`;
    out.push(`# ── ${title} ${'─'.repeat(Math.max(3, 74 - title.length))}`);
    out.push(...comment(m.description));
    out.push('');
    let any = false;
    for (const e of rest) {
      if (written.has(e.key)) {
        if (m !== core) { out.push(`# ${e.key}: set above.`, ''); any = true; }
        continue;
      }
      out.push(...entry(e, e.required && !m.alwaysOn ? ' (Required when this feature is on.)' : ''), '');
      written.add(e.key);
      any = true;
    }
    if (!any) out.push('# (no settings)', '');
  }
  return out.join('\n').replace(/\n+$/, '\n');
}

export function undocumentedEnvKeys(): Array<[string, string[]]> {
  const documented = new Set(MODULES.flatMap((m) => m.env.map((e) => e.key)));
  return [...scanEnvKeys(ROOT).entries()].filter(([key]) => !documented.has(key));
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const missing = undocumentedEnvKeys();
  if (missing.length) {
    console.error('These settings are read by the code but not listed in any module (src/modules.ts):');
    for (const [key, files] of missing) console.error(`  ${key}  (${files.join(', ')})`);
    process.exit(1);
  }
  const text = renderEnvExample();
  const path = join(ROOT, '.env.example');
  if (process.argv.includes('--check')) {
    const { readFileSync } = await import('fs');
    const current = (() => { try { return readFileSync(path, 'utf8'); } catch { return ''; } })();
    if (current !== text) { console.error('.env.example is out of date; run npm run env:example'); process.exit(1); }
    console.log('.env.example is up to date and covers every setting the code reads.');
  } else {
    writeFileSync(path, text);
    console.log(`wrote ${path}`);
  }
}
