import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// ─────────────────────────────────────────────────────────────────────────────
// Profile config — the single source of truth for who this assistant is and who
// it serves. Generated by `npm run onboard` (the Mirror conversation) into
// config/profile.json (gitignored). The repo ships config/profile.example.json.
//
// Everything that used to be hardcoded to one person (bot name, owner name,
// family name, inner circle, which groups exist) reads from here. When no
// profile.json is present the loader returns safe, generic defaults so the repo
// still typechecks and boots — `initUsers()` won't throw on a fresh clone.
// ─────────────────────────────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROFILE_PATH = process.env.ASSISTANT_PROFILE_PATH?.trim()
  || join(ROOT, 'config', 'profile.json');

export type Tone = 'direct' | 'warm' | 'playful';
export type Role = 'admin' | 'member' | 'child';

export interface Pronouns {
  subject: string;
  object: string;
  possessive: string;
}

export const DEFAULT_PRONOUNS: Pronouns = { subject: 'they', object: 'them', possessive: 'their' };

/** A person who can message the assistant (resolves from a phone/email handle). */
export interface ProfileUser {
  id: string;
  name: string;
  /** Full name for phone calls and bookings ("Alex Rivera"). Falls back to `name`. */
  fullName?: string;
  /** Casual short name ("Alex"). Falls back to `name`. */
  shortName?: string;
  /** Pronouns used in prompts. Defaults to they/them/their. */
  pronouns?: Pronouns;
  tone: Tone;
  role: Role;
  /** Registry keys of the groups this user may use. */
  allowedGroups: string[];
  /** Env var holding this user's phone (default `USER_<ID uppercased>`). */
  phoneEnv?: string;
  /** Env var holding this user's email (default `USER_<ID uppercased>_EMAIL`). */
  emailEnv?: string;
}

/** A person in the CRM seed (inner circle). Not necessarily a messaging user. */
export interface ProfilePerson {
  name: string;
  relationship?: string;
  role?: string;
  notes?: string;
}

export interface ProfileConfig {
  /** What the assistant is called (e.g. "Assistant"). */
  botName: string;
  /** The @-trigger required in group chats (e.g. "@assistant"). */
  triggerWord: string;
  /** A collective noun for the household/team, used in the soul line. */
  householdName: string;
  /** The admin user — all system-initiated work runs as this user. */
  owner: ProfileUser;
  /** Additional messaging users (e.g. a partner). */
  members: ProfileUser[];
  /** CRM seed people written by the seed script. */
  people: ProfilePerson[];
  /** Group registry keys this deployment turns on. */
  groupsEnabled: string[];
  /** Feature switchboard: module id -> on/off (see src/modules.ts). Absent = module defaults. */
  modules?: Record<string, boolean>;
  /** IANA timezone the assistant lives in (e.g. "America/Chicago"). See getTimezone(). */
  timezone?: string;
  /** Local hours when proactive messages wait (default 21 → 7). */
  quietHours?: { start: number; end: number };
}

// Generic, person-free defaults. A fresh clone with no profile.json still boots.
const DEFAULTS: ProfileConfig = {
  botName: 'Assistant',
  triggerWord: process.env.TRIGGER_WORD || '@assistant',
  householdName: 'household',
  owner: {
    id: 'owner',
    name: 'Owner',
    tone: 'direct',
    role: 'admin',
    allowedGroups: ['admin', 'family', 'work', 'health', 'reflection', 'brain-pulse'],
    phoneEnv: 'USER_OWNER',
    emailEnv: 'USER_OWNER_EMAIL',
  },
  members: [],
  people: [],
  groupsEnabled: ['admin'],
};

let cached: ProfileConfig | null = null;
let cachedTimezone: string | null = null;

function normalizePronouns(raw: any): Pronouns | undefined {
  if (!raw || typeof raw !== 'object') return undefined;
  const subject = String(raw.subject || '').trim();
  const object = String(raw.object || '').trim();
  const possessive = String(raw.possessive || '').trim();
  if (!subject || !object || !possessive) return undefined;
  return { subject, object, possessive };
}

/** Keep only `id: boolean` entries (also accepts "true"/"false"/"on"/"off" strings). */
export function normalizeModules(raw: unknown): Record<string, boolean> | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined;
  const out: Record<string, boolean> = {};
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    const key = id.trim();
    if (!key) continue;
    if (typeof value === 'boolean') out[key] = value;
    else if (typeof value === 'string' && ['true', 'on'].includes(value.trim().toLowerCase())) out[key] = true;
    else if (typeof value === 'string' && ['false', 'off'].includes(value.trim().toLowerCase())) out[key] = false;
  }
  return out;
}

function normalizeUser(raw: any, fallbackId: string): ProfileUser {
  const id = String(raw?.id || fallbackId);
  const pronouns = normalizePronouns(raw?.pronouns);
  return {
    id,
    name: String(raw?.name || id),
    ...(raw?.fullName ? { fullName: String(raw.fullName) } : {}),
    ...(raw?.shortName ? { shortName: String(raw.shortName) } : {}),
    ...(pronouns ? { pronouns } : {}),
    tone: (raw?.tone as Tone) || 'direct',
    role: (raw?.role as Role) || (fallbackId === 'owner' ? 'admin' : 'member'),
    allowedGroups: Array.isArray(raw?.allowedGroups) ? raw.allowedGroups.map(String) : [],
    phoneEnv: raw?.phoneEnv || `USER_${id.toUpperCase()}`,
    emailEnv: raw?.emailEnv || `USER_${id.toUpperCase()}_EMAIL`,
  };
}

function normalizeQuietHours(raw: any): { start: number; end: number } | undefined {
  if (!raw || typeof raw !== 'object') return undefined;
  const start = Number(raw.start);
  const end = Number(raw.end);
  const ok = (n: number) => Number.isInteger(n) && n >= 0 && n <= 23;
  return ok(start) && ok(end) ? { start, end } : undefined;
}

/** Load (and cache) the profile config, falling back to generic defaults. */
export function getProfileConfig(): ProfileConfig {
  if (cached) return cached;

  if (!existsSync(PROFILE_PATH)) {
    cached = DEFAULTS;
    return cached;
  }

  try {
    const raw = JSON.parse(readFileSync(PROFILE_PATH, 'utf-8'));
    cached = {
      botName: String(raw.botName || DEFAULTS.botName),
      triggerWord: String(raw.triggerWord || process.env.TRIGGER_WORD || DEFAULTS.triggerWord),
      householdName: String(raw.householdName || DEFAULTS.householdName),
      owner: normalizeUser(raw.owner, 'owner'),
      members: Array.isArray(raw.members)
        ? raw.members.map((m: any, i: number) => normalizeUser(m, m?.id || `member${i + 1}`))
        : [],
      people: Array.isArray(raw.people) ? raw.people : [],
      groupsEnabled: Array.isArray(raw.groupsEnabled) ? raw.groupsEnabled.map(String) : DEFAULTS.groupsEnabled,
      modules: normalizeModules(raw.modules),
      ...(typeof raw.timezone === 'string' && raw.timezone.trim() ? { timezone: raw.timezone.trim() } : {}),
      ...(normalizeQuietHours(raw.quietHours) ? { quietHours: normalizeQuietHours(raw.quietHours)! } : {}),
    };
    return cached;
  } catch (err) {
    console.warn(`[config] failed to parse ${PROFILE_PATH}, using defaults:`, (err as Error).message);
    cached = DEFAULTS;
    return cached;
  }
}

/** Reset the in-memory cache (used by onboarding after it writes a new profile). */
export function resetProfileCache(): void {
  cached = null;
  cachedTimezone = null;
}

export function getBotName(): string {
  return getProfileConfig().botName;
}

export function getOwner(): ProfileUser {
  return getProfileConfig().owner;
}

/** How prompts should refer to the owner: name, full name, and pronouns. */
export function ownerRef(): { name: string; fullName: string; pronouns: Pronouns } {
  const owner = getOwner();
  return {
    name: owner.shortName || owner.name,
    fullName: owner.fullName || owner.name,
    pronouns: owner.pronouns || DEFAULT_PRONOUNS,
  };
}

/** Local quiet hours (proactive messages wait). Defaults to 21:00 → 07:00. */
export function getQuietHours(): { start: number; end: number } {
  return getProfileConfig().quietHours || { start: 21, end: 7 };
}

// ── Timezone ────────────────────────────────────────────────────────────────
// One place decides which clock the assistant lives on: profile.timezone, then
// ASSISTANT_TIMEZONE, then the host's zone, then America/New_York as a last
// resort. Every cron, date table, and calendar write reads getTimezone().

export const FALLBACK_TIMEZONE = 'America/New_York';


export function isValidTimezone(tz: string | undefined | null): tz is string {
  if (!tz || typeof tz !== 'string') return false;
  try {
    new Intl.DateTimeFormat('en', { timeZone: tz });
    return true;
  } catch {
    return false;
  }
}

export function getTimezone(): string {
  if (cachedTimezone) return cachedTimezone;
  const candidates: Array<[string, string | undefined]> = [
    ['profile.timezone', getProfileConfig().timezone],
    ['ASSISTANT_TIMEZONE', process.env.ASSISTANT_TIMEZONE?.trim()],
    ['host', (() => { try { return Intl.DateTimeFormat().resolvedOptions().timeZone; } catch { return undefined; } })()],
  ];
  for (const [source, tz] of candidates) {
    if (!tz) continue;
    if (isValidTimezone(tz)) {
      cachedTimezone = tz;
      return tz;
    }
    console.warn(`[config] ignoring invalid timezone from ${source}: ${tz}`);
  }
  cachedTimezone = FALLBACK_TIMEZONE;
  return cachedTimezone;
}
