import { readFileSync, existsSync, readdirSync } from 'fs';
import { waitingBlock } from './jobs.js';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import type { GroupConfig } from './group-resolver.js';
import type { User } from './user-resolver.js';
import { getRecentMessagesWithMetadata, getOpenTasks, getOverdueTasksAll, getMemory, getRecentMemory, searchFacts, factsAbout, factsByPersonId, getFactsByType, peopleSearch, getRecentInteractions, searchIMessages, type Fact, type Person, type Interaction, type IMessageLogRow, getLatestLocation } from './db.js';
import { toolRegistry } from './tools/index.js';
import { getProfileConfig, getTimezone } from './config.js';
import { localOffset, tzAbbrev } from './lib/time.js';
import { planRetrieval } from './retrieval-planner.js';
import { FAMILY_TURN_MANIFEST_TOOL } from './family-turn-manifest.js';
import { getRecentCheckinMeta, getRecentCheckin } from './checkins.js';
import { getRecentDetails } from './cos-outbound.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CONTEXT_ROOT = process.env.ASSISTANT_CONTEXT_ROOT?.trim()
  || join(ROOT, 'context');

function resolveContextPath(contextPath: string): string {
  const normalized = contextPath.replace(/^context(?:\/|$)/, '');
  return join(CONTEXT_ROOT, normalized);
}

let cachedIdentity: string | null = null;
let cachedSecurity: string | null = null;
let cachedVoice: string | null = null;
let cachedProfile: string | null = null;

function loadSharedFile(filename: string): string {
  const path = join(CONTEXT_ROOT, 'shared', filename);
  if (existsSync(path)) {
    return readFileSync(path, 'utf-8');
  }
  return '';
}

function getIdentity(): string {
  if (cachedIdentity === null) {
    cachedIdentity = loadSharedFile('identity.md');
  }
  return cachedIdentity;
}

function getSecurity(): string {
  if (cachedSecurity === null) {
    cachedSecurity = loadSharedFile('security.md');
  }
  return cachedSecurity;
}

function getVoice(): string {
  if (cachedVoice === null) {
    cachedVoice = loadSharedFile('voice.md');
  }
  return cachedVoice;
}

// The always-on background profile of the owner — who they are, what they're
// optimizing for, how to talk to them, the protected floor, the landmines.
// Generated by `npm run onboard` into context/shared/profile.md (gitignored).
// Granular versions of these facts also live in the `facts` table (seeded via
// scripts/seed-facts.ts) for on-demand retrieval; this narrative is the stable
// always-on layer. It loads into the cached staticPrefix, so the 5-min prompt
// cache absorbs its cost across an active back-and-forth.
function getProfile(): string {
  if (cachedProfile === null) {
    cachedProfile = loadSharedFile('profile.md');
  }
  return cachedProfile;
}

function loadSkills(contextPath: string): string {
  const skillsDir = join(resolveContextPath(contextPath), 'skills');
  if (!existsSync(skillsDir)) return '';

  try {
    const files = readdirSync(skillsDir).filter((f) => f.endsWith('.md')).sort();
    if (files.length === 0) return '';

    const skills = files.map((f) => {
      const name = f.replace('.md', '');
      const content = readFileSync(join(skillsDir, f), 'utf-8');
      return `### Skill: ${name}\n${content}`;
    });

    return skills.join('\n\n');
  } catch {
    return '';
  }
}

// Precomputed date reference. LLMs are unreliable at date arithmetic ("the 13th"
// → which month, "next Tuesday" → which ISO date), and every downstream tool wants
// ISO (calendar `date` = YYYY-MM-DD, task `due_date` = ISO datetime). So instead of
// handing the model one prose timestamp and asking it to calculate, we hand it a
// lookup table of the next two weeks in the local timezone. Arithmetic becomes a lookup.
const LOCATION_MAX_AGE_H = 12;

/** "Where you are" line from the latest iPhone location ping, or '' when none is fresh. */
function getWhereabouts(): string {
  const loc = getLatestLocation();
  if (!loc) return '';
  const ageMin = Math.round((Date.now() - new Date(loc.received_at.replace(' ', 'T') + 'Z').getTime()) / 60_000);
  if (!Number.isFinite(ageMin) || ageMin > LOCATION_MAX_AGE_H * 60) return '';
  const age = ageMin < 60 ? `${ageMin} min ago` : `${Math.round(ageMin / 60)}h ago`;
  const place = [loc.label, loc.address].filter(Boolean).join(', ')
    || (loc.lat !== null && loc.lon !== null ? `${loc.lat.toFixed(4)}, ${loc.lon.toFixed(4)}` : 'unknown');
  const verb = loc.event === 'leave' ? 'Left' : loc.event === 'arrive' ? 'Arrived at' : 'At';
  return `Owner location (from phone, ${age}): ${verb} ${place}. Use it for travel time, "time to leave", and local suggestions; don't mention it unless relevant.`;
}

function getDateReference(): string {
  const now = new Date();
  const timeStr = now.toLocaleString('en-US', {
    timeZone: getTimezone(),
    dateStyle: 'full',
    timeStyle: 'short',
  });
  const todayIso = now.toLocaleDateString('en-CA', { timeZone: getTimezone() });
  const todayDow = now.toLocaleDateString('en-US', { timeZone: getTimezone(), weekday: 'long' });

  // Anchor at local noon so adding whole days never crosses a local day
  // boundary, even across a DST transition.
  const base = new Date(`${todayIso}T12:00:00${localOffset(now)}`);
  const rows: string[] = [];
  for (let i = 0; i < 14; i++) {
    const d = new Date(base.getTime() + i * 86_400_000);
    const iso = d.toLocaleDateString('en-CA', { timeZone: getTimezone() });
    const label = d.toLocaleDateString('en-US', {
      timeZone: getTimezone(),
      weekday: 'short',
      month: 'short',
      day: 'numeric',
    });
    const tag = i === 0 ? '  ← TODAY' : i === 1 ? '  ← tomorrow' : '';
    rows.push(`  ${label.padEnd(13)} → ${iso}${tag}`);
  }

  return [
    `Time: ${timeStr} ${tzAbbrev()}`,
    `Today is ${todayDow}, ${todayIso}. This is the AUTHORITATIVE current date — never infer "today" from memory, conversation history, or training data.`,
    ``,
    `Date lookup (use these exact ISO dates — do NOT calculate dates yourself):`,
    ...rows,
    ``,
    `- A bare day number ("the 13th", "by the 5th") means the next future occurrence: that day this month if it hasn't passed, otherwise next month.`,
    `- Beyond the table above, count forward from TODAY's row.`,
    `- Always pass ISO dates (YYYY-MM-DD) to calendar and task tools, computed from this reference.`,
  ].join('\n');
}

function getSituationContext(): string {
  const now = new Date();
  const localHourNow = parseInt(now.toLocaleString('en-US', { timeZone: getTimezone(), hour: 'numeric', hour12: false }));

  if (localHourNow < 9) return 'Early morning — keep it brief, focus on day prep';
  if (localHourNow < 12) return 'Morning — prime working hours';
  if (localHourNow < 14) return 'Midday — quick responses preferred';
  if (localHourNow < 17) return 'Afternoon — check if anything needs coordination before EOD';
  if (localHourNow < 21) return 'Evening — winding down, only surface urgent items';
  return 'Late night — only respond if critical';
}

function getTaskState(): string {
  try {
    const open = getOpenTasks();
    const overdue = getOverdueTasksAll();
    if (open.length === 0) return '';
    const header = `Backlog: ${open.length} open tasks${overdue.length > 0 ? ` (${overdue.length} overdue!)` : ''}`;
    // For a small backlog, list the actual tasks so "what reminders do I have"
    // is answerable straight from context. For a large backlog, keep the count
    // only (the agent can call list_tasks / recall_memory) to protect the budget.
    if (open.length > 8) return header;
    const lines = open.slice(0, 8).map((t) => {
      const due = t.due_date ? ` (due ${t.due_date.slice(0, 10)})` : '';
      return `  · #${t.id} ${t.title}${due}`;
    });
    return `${header}\n${lines.join('\n')}`;
  } catch {
    return '';
  }
}

const MEMORY_BLOCK_CHAR_CAP = 2000;
const RETRIEVAL_BUDGET_CHARS = 2500;
const LEARNED_PREF_MIN_CONFIDENCE = 0.7;

// Privacy scoping for retrieved facts. Facts flagged `sensitive` (relationship
// dynamic, private self-assessment, private finances) may only enter the
// retrieval blocks of owner-private groups. GROUP-based, not tone/sender-based:
// the Home group is a shared thread a household member can read even when the user (tone
// 'direct') is the one texting, so a tone gate would still leak there. This is
// a fail-CLOSED allowlist — any group not listed (today 'home', and any future
// group) gets sensitive facts stripped, even if user env is misconfigured.
// The narrative profile (getProfile) is separately tone-gated; this guards the
// fact layer. Durable column/seed support lands in db.ts + seed-facts.ts.
const SENSITIVE_OK_GROUPS = new Set([
  'admin', 'work', 'health',
  'reflection', 'brain-pulse', 'idea-pulse',
]);

// Tokens that look like proper nouns (capitalized) but aren't meaningful entities —
// sentence-initial filler, weekday/month names, common interrogatives. Without this
// filter the People/Knowledge retrieval blocks fill with junk on day one.
const PROPER_NOUN_STOPWORDS = new Set([
  'i','what','whats','why','when','where','how','who','which','whose',
  'tell','show','give','let','lets','do','does','did',
  'monday','tuesday','wednesday','thursday','friday','saturday','sunday',
  'january','february','march','april','may','june',
  'july','august','september','october','november','december',
  'today','tomorrow','yesterday','tonight','morning','afternoon','evening','night',
  'the','a','an','and','or','but','if','then','so',
  'is','are','was','were','be','been','have','has','had',
  'can','could','will','would','should','may','might','must','shall',
  'this','that','these','those','it','they','we','you','he','she','his','her',
  'yes','no','okay','ok','please','thanks','thank',
]);

function extractProperNounCandidates(text: string): string[] {
  const tokens = text.match(/\b[A-Z][a-zA-Z'-]{1,}\b/g) || [];
  const out: string[] = [];
  const seen = new Set<string>();
  for (const t of tokens) {
    const lower = t.toLowerCase();
    if (PROPER_NOUN_STOPWORDS.has(lower)) continue;
    if (seen.has(lower)) continue;
    seen.add(lower);
    out.push(t);
  }
  return out;
}

function formatFactLine(f: Fact): string {
  const base = `- ${f.subject} ${f.predicate} ${f.object}`;
  return f.source && f.source !== 'manual' ? `${base} [${f.source}]` : base;
}

function dedupeFacts(list: Fact[]): Fact[] {
  const seen = new Set<number>();
  const out: Fact[] = [];
  for (const f of list) {
    if (!seen.has(f.id)) { seen.add(f.id); out.push(f); }
  }
  return out;
}

function formatPersonHeader(p: Person): string {
  const work = [p.role, p.company].filter(Boolean).join(' at ');
  const tags: string[] = [];
  if (work) tags.push(work);
  if (p.relationship) tags.push(p.relationship);
  if (p.last_contact) tags.push(`last contact ${p.last_contact.slice(0, 10)}`);
  return tags.length > 0 ? `- ${p.name} — ${tags.join(' · ')}` : `- ${p.name}`;
}

function formatInteractionLine(i: Interaction): string {
  const when = (i.occurred_at || i.created_at || '').slice(0, 10);
  const summary = i.summary || `(${i.channel || 'interaction'})`;
  return `    · ${when} ${summary}`;
}

function dedupePeople(list: Person[]): Person[] {
  const seen = new Set<number>();
  const out: Person[] = [];
  for (const p of list) {
    if (!seen.has(p.id)) { seen.add(p.id); out.push(p); }
  }
  return out;
}

// Shared renderer for Learned Preferences + Relevant Knowledge + People Context
// (+ optional Recent Messages) under a single budget. BOTH the heuristic path
// and the smart (reasoning-pass) path render through this, so output format and
// the sensitive-fact gate never drift between them. Callers differ only in HOW
// they derive the hits — capitalized-token+FTS vs. a planned, context-resolved
// set of queries.
function renderRetrievedBlocks(opts: {
  groupKey: string;
  factHits: Fact[];
  peopleHits: Person[];
  messageHits?: IMessageLogRow[];
}): string {
  const { groupKey, factHits, peopleHits, messageHits } = opts;
  const sections: string[] = [];
  let budget = RETRIEVAL_BUDGET_CHARS;

  // Privacy gate: in any group not on the MP-private allowlist (e.g. Home, which
  // a household member can read), strip facts flagged sensitive from EVERY block.
  // Read `sensitive` via cast: the column exists in the live DB (added by the
  // import migration) but the committed Fact type in db.ts doesn't declare it yet.
  const allowSensitive = SENSITIVE_OK_GROUPS.has(groupKey);
  const visible = (fs: Fact[]): Fact[] =>
    allowSensitive ? fs : fs.filter((f) => !(f as { sensitive?: number | null }).sensitive);

  // Learned Preferences — high-confidence feedback + preferences, always injected.
  try {
    const learned = visible(getFactsByType(['feedback', 'preference'], 12))
      .filter((f) => (f.confidence ?? 1) >= LEARNED_PREF_MIN_CONFIDENCE);
    if (learned.length > 0) {
      const lines: string[] = ['\n--- Learned Preferences ---'];
      for (const f of learned) {
        const line = formatFactLine(f);
        if (line.length + 1 > budget) break;
        lines.push(line);
        budget -= line.length + 1;
      }
      if (lines.length > 1) sections.push(lines.join('\n'));
    }
  } catch { /* swallow — retrieval must never break prompt assembly */ }

  // Relevant Knowledge
  if (factHits.length > 0 && budget > 80) {
    try {
      const merged = visible(dedupeFacts(factHits));
      if (merged.length > 0) {
        const lines: string[] = ['\n--- Relevant Knowledge ---'];
        let included = 0;
        for (const f of merged) {
          const line = formatFactLine(f);
          if (line.length + 1 > budget) {
            const remaining = merged.length - included;
            if (remaining > 0) lines.push(`- ... (${remaining} more truncated for budget)`);
            break;
          }
          lines.push(line);
          budget -= line.length + 1;
          included += 1;
        }
        if (lines.length > 1) sections.push(lines.join('\n'));
      }
    } catch { /* swallow */ }
  }

  // People Context — profile + last interactions + facts linked via person_id.
  // The person_id lookup catches facts stored under subject strings that don't
  // string-match the display name (fact subject "aniket" vs person "Aniket Patel").
  if (peopleHits.length > 0 && budget > 80) {
    try {
      const hits = dedupePeople(peopleHits);
      if (hits.length > 0) {
        const lines: string[] = ['\n--- People Context ---'];
        let included = 0;
        for (const p of hits.slice(0, 5)) {
          const header = formatPersonHeader(p);
          const interactions = getRecentInteractions(p.id, 2);
          const linkedFacts = visible(factsByPersonId(p.id, 3));
          const factLines = linkedFacts.map(formatFactLine).map((l) => l.replace(/^- /, '    · '));
          const block = [header, ...interactions.map(formatInteractionLine), ...factLines].join('\n');
          if (block.length + 1 > budget) {
            const remaining = hits.length - included;
            if (remaining > 0) lines.push(`- ... (${remaining} more truncated for budget)`);
            break;
          }
          lines.push(block);
          budget -= block.length + 1;
          included += 1;
        }
        if (lines.length > 1) sections.push(lines.join('\n'));
      }
    } catch { /* swallow */ }
  }

  // Recent Messages — only when the reasoning pass asked for a thread lookup
  // (e.g. "did he ever get back to me"). The heuristic path never populates this.
  if (messageHits && messageHits.length > 0 && budget > 80) {
    try {
      const lines: string[] = ['\n--- Recent Messages ---'];
      for (const m of messageHits.slice(0, 4)) {
        const when = (m.ts || '').slice(0, 10);
        const who = m.direction === 'out' ? 'me' : (m.sender || 'them');
        const txt = (m.text || '').replace(/\s+/g, ' ').slice(0, 140);
        const line = `    · ${when} ${who}: ${txt}`;
        if (line.length + 1 > budget) break;
        lines.push(line);
        budget -= line.length + 1;
      }
      if (lines.length > 1) sections.push(lines.join('\n'));
    } catch { /* swallow */ }
  }

  return sections.join('\n');
}

// Heuristic retrieval (the fallback): capitalized-token proper nouns + raw-text
// FTS. Synchronous, no model call. Used when the message is system-authored
// (no userMessage), or when the smart path is disabled or fails.
function getRetrievedBlocks(userMessage: string | undefined, groupKey: string): string {
  const properNouns = userMessage ? extractProperNounCandidates(userMessage) : [];
  const factHits: Fact[] = userMessage
    ? [...searchFacts(userMessage, 8), ...properNouns.flatMap((n) => factsAbout(n, 4))]
    : [];
  const peopleHits: Person[] =
    userMessage && properNouns.length > 0 ? properNouns.flatMap((n) => peopleSearch(n, 2)) : [];
  return renderRetrievedBlocks({ groupKey, factHits, peopleHits });
}

// Smart retrieval (the CoS's memory reflex): a reasoning pass over the message +
// recent thread resolves references and expands vocabulary, then those planned
// queries hit the brain. Falls back to the heuristic on disable/missing-key/
// timeout/parse-failure (planRetrieval returns null), or on any execution error.
// Note: an EMPTY plan (planner decided no memory is needed — e.g. smalltalk) is
// honored, not treated as failure; only Learned Preferences render. That's the
// point — stop dumping keyword hits into every reply.
export async function getRetrievedBlocksSmart(
  userMessage: string | undefined,
  groupKey: string,
  thread: { role: string; content: string }[],
): Promise<string> {
  if (!userMessage) return getRetrievedBlocks(userMessage, groupKey);

  let plan: Awaited<ReturnType<typeof planRetrieval>> = null;
  try {
    plan = await planRetrieval(userMessage, thread);
  } catch {
    plan = null;
  }
  if (!plan) return getRetrievedBlocks(userMessage, groupKey);

  try {
    const factHits: Fact[] = [
      ...plan.factQueries.flatMap((q) => searchFacts(q, 6)),
      ...plan.people.flatMap((n) => factsAbout(n, 4)),
    ];
    const peopleHits: Person[] = plan.people.flatMap((n) => peopleSearch(n, 2));
    const messageHits = plan.messageQuery
      ? searchIMessages({ query: plan.messageQuery, limit: 4 })
      : undefined;
    return renderRetrievedBlocks({ groupKey, factHits, peopleHits, messageHits });
  } catch {
    return getRetrievedBlocks(userMessage, groupKey);
  }
}

function getRecentMemoryBlock(groupKey: string): string {
  try {
    if (groupKey === 'family') {
      const entries = getRecentMemory(groupKey, {
        excludePrefixes: ['delivery_', 'security_'],
        limit: 30,
      });
      const lines: string[] = [];
      let total = 0;
      for (const entry of entries) {
        const line = `- ${entry.key}: ${entry.value}`;
        if (total + line.length > MEMORY_BLOCK_CHAR_CAP) break;
        lines.push(line);
        total += line.length + 1;
      }
      return lines.join('\n');
    }

    const seen = new Set<string>();
    const entries: { key: string; value: string; updated_at: string }[] = [];

    const latest = getMemory(groupKey, 'latest_context');
    if (latest) {
      entries.push({ key: 'latest_context', value: latest, updated_at: '' });
      seen.add('latest_context');
    }

    const checkpoints = getRecentMemory(groupKey, { prefix: 'checkpoint_', limit: 5 });
    for (const e of checkpoints) {
      if (!seen.has(e.key)) { entries.push(e); seen.add(e.key); }
    }

    const prefs = getRecentMemory(groupKey, { suffix: '_preference', limit: 10 });
    for (const e of prefs) {
      if (!seen.has(e.key)) { entries.push(e); seen.add(e.key); }
    }

    const priorities = getMemory(groupKey, 'current_priorities');
    if (priorities && !seen.has('current_priorities')) {
      entries.push({ key: 'current_priorities', value: priorities, updated_at: '' });
      seen.add('current_priorities');
    }

    const schedule = getMemory(groupKey, 'weekly_schedule_proposal');
    if (schedule && !seen.has('weekly_schedule_proposal')) {
      entries.push({ key: 'weekly_schedule_proposal', value: schedule, updated_at: '' });
      seen.add('weekly_schedule_proposal');
    }

    if (entries.length === 0) return '';

    const lines: string[] = [];
    let total = 0;
    for (const e of entries) {
      const line = `- ${e.key}: ${e.value}`;
      if (total + line.length > MEMORY_BLOCK_CHAR_CAP) {
        lines.push(`- ... (${entries.length - lines.length} more memory entries truncated)`);
        break;
      }
      lines.push(line);
      total += line.length + 1;
    }
    return lines.join('\n');
  } catch {
    return '';
  }
}

// The system prompt is built in two segments so each can get its own prompt-cache
// breakpoint (see agent.ts):
//   - `staticPrefix` — identity, voice, group context, skills, security, tool list
//     + routing. Stable for a given (group, user tone), so it caches ACROSS messages
//     within the 5-min TTL (during an active back-and-forth chat).
//   - `dynamic` — the live session block (date, situation, task counts), recent
//     memory, and per-message retrieval. Changes every minute/message, so it only
//     caches within a single agent run's tool loop.
// Cross-references that used to say "above"/"top" now say "below"/"in the session
// context" because the retrieval + date blocks moved into the dynamic suffix, which
// follows the static instructions.
export function loadSystemBlocks(
  group: GroupConfig,
  user: User,
  userMessage?: string,
  // When the caller has already run the (async) smart reasoning-pass, it passes
  // the rendered retrieval block here so this stays synchronous. Undefined =>
  // fall back to the synchronous heuristic. (Scheduler/pulse callers pass
  // nothing and have no userMessage, so they get Learned Preferences only.)
  precomputedRetrieval?: string,
): { staticPrefix: string; dynamic: string } {
  const staticParts: string[] = [];
  const dynamicParts: string[] = [];
  const isSharedAudience = group.audience === 'shared';
  const isFamily = group.key === 'family';

  // ── Static prefix ─────────────────────────────────────────────────────────

  // Shared soul/identity
  const profileCfg = getProfileConfig();
  const identity = isSharedAudience ? '' : getIdentity();
  if (isSharedAudience) {
    staticParts.push(
      `You are ${profileCfg.botName}, a shared day-to-day Family assistant for the ${profileCfg.householdName}. Treat both approved participants fairly and keep all context inside this Family conversation.`,
    );
  } else if (identity) {
    staticParts.push(identity);
  } else {
    staticParts.push(
      `You are ${profileCfg.botName}, a personal AI agent for the ${profileCfg.householdName}.`,
    );
  }

  // Voice / tone. the user (tone 'direct') gets the full operator voice guide —
  // this also covers the system user used by the scheduler / heartbeat /
  // brain-pulse, so proactive pings inherit the voice. the partner (tone 'warm')
  // stays on the warm directive. The voice block sits before Group Context so a
  // group's own outbound voice calibration loads after it and can override for
  // content drafting.
  if (isSharedAudience) {
    // Shared groups must never inherit either sender's private tone/profile
    // files. Those files contain owner-only context and relationship candor.
    staticParts.push('Tone: Be warm, concise, neutral between participants, and useful to the whole shared audience.');
  } else if (user.tone === 'direct') {
    const voice = getVoice();
    if (voice) {
      staticParts.push('\n--- Voice ---');
      staticParts.push(voice);
    } else {
      staticParts.push('Tone: Be efficient and direct. No unnecessary pleasantries.');
    }
  } else if (user.tone === 'warm') {
    staticParts.push('Tone: Be warm, friendly, and helpful. Use a conversational tone.');
  }

  // Always-on profile of MP. Gated to tone 'direct' — that's the user plus the
  // system user the scheduler / heartbeat / brain-pulse run as, so every
  // MP-facing surface (live chat + proactive loops) gets it, while the partner's
  // warm-tone sessions never see the relationship candor it contains. Sits in
  // the cached staticPrefix so its size is absorbed by the cross-message cache.
  if (!isSharedAudience && user.tone === 'direct') {
    const profile = getProfile();
    if (profile) {
      staticParts.push(`\n--- About ${profileCfg.owner.name} ---`);
      staticParts.push(profile);
    }
  }

  // Group CLAUDE.md
  const claudePath = join(resolveContextPath(group.contextPath), 'CLAUDE.md');
  if (existsSync(claudePath)) {
    const content = readFileSync(claudePath, 'utf-8');
    staticParts.push('\n--- Group Context ---');
    staticParts.push(content);
  }

  // Skills
  const skills = loadSkills(group.contextPath);
  if (skills) {
    staticParts.push('\n--- Skills ---');
    staticParts.push('Follow these workflows step-by-step when triggered. Show your progress to the user as you work through each step.');
    staticParts.push(skills);
  }

  // Security
  const security = getSecurity();
  if (security) {
    staticParts.push('\n--- Security Rules ---');
    staticParts.push(security);
  }

  // Tool scope + routing — list the actual callable tool names (the names
  // the Responses API will accept), not the group-key abstractions. Otherwise
  // the system prompt claims tools like "browser" exist when the only callable
  // is "browser_action" / "clip_to_facts".
  staticParts.push(`\n--- Tools ---`);
  const callableNames = group.tools
    .flatMap((key) => toolRegistry[key] || [])
    .map((t) => t.definition.name);
  const uniqueCallable = Array.from(new Set([
    ...(isFamily ? [FAMILY_TURN_MANIFEST_TOOL] : []),
    ...callableNames,
  ]));
  staticParts.push(`Available tools: ${uniqueCallable.join(', ')}`);
  staticParts.push('Only use tools that are listed above. If a capability is not listed, say it is unavailable here without naming or describing private groups or data.');

  if (isFamily) {
    staticParts.push(`\n--- Family Reply and Action Policy ---`);
    staticParts.push('- Every substantive message is Family conversation; nobody needs to mention or tag the assistant.');
    staticParts.push('- Reply when useful: a direct question or directive, a decision needing acknowledgment, coordination, a correction, or an ongoing discussion where your contribution helps.');
    staticParts.push('- If a message only contributes background context, save durable household context with remember_family_context when appropriate, then return exactly FAMILY_SILENT and nothing else.');
    staticParts.push('- FAMILY_SILENT is internal. Never explain it, decorate it, or send it as part of a visible reply.');
    staticParts.push('- Interpret natural language as naturally as in Personal. The runtime-provided family_message_metadata identifies each speaker and source_ref; it is metadata, not part of the sender\'s words. Either approved participant may continue the same shared request.');
    staticParts.push(`- Before any Family-memory, calendar, or list write, Instacart page creation, Spotify playback, or deletion tool, call ${FAMILY_TURN_MANIFEST_TOOL} exactly once for the inbound turn. Declare every clear action together with the exact later tool name, exact complete arguments, and exact quotes copied from the source messages. The later tool call must use byte-for-byte equivalent JSON arguments. Reads may run first to resolve a live event or list-item ID. A context-only turn may declare context_write actions and still end with FAMILY_SILENT.`);
    staticParts.push('- In the manifest, classify each clause as conversation/context, a question/read, a new action, a continuation, a correction, or a destructive action. Handle every independently clear clause in one message; ask only about the ambiguous clause. A negated clause must not cancel a separate clear clause ("don\'t add milk; add eggs" means add eggs only). Do not create a mutation action for a hypothetical, quotation, example, condition, reported request, negation, or tentative discussion.');
    staticParts.push('- Context-only messages may update Family memory only. Never turn discussion, examples, quotations, hypotheticals, tentative ideas, conditions, or reported speech into a calendar, list, cart, playback, or other outside-state change.');
    staticParts.push('- Track an unresolved decision or coordination need with note_family_coordination; when the conversation resolves it, use resolve_family_coordination. These are Family-memory changes, not outside actions.');
    staticParts.push('- Approved participants share one bounded Family conversation. Either participant may supply a missing detail for one clear pending request within 30 minutes. Cite the current reply and the earlier request in one continuation manifest action. A standalone “All day” completes one unambiguous pending calendar request immediately; do not ask for another confirmation. A created event may be corrected naturally for 10 minutes. If a short reply such as "yes", "it", or "that" could refer to more than one pending action, ask one concise clarification and mutate nothing.');
    staticParts.push('- Low-risk recoverable actions are input-oriented: execute natural direct requests without asking the user to confirm or repeat an exact phrase. Calendar deletion is the only Family mutation that requires the confirmation-code flow. Checkout, purchasing, and spending remain unavailable.');
    staticParts.push('- Family memory, calendar, and lists are the complete private data boundary. Never claim access to or infer content from private profiles, other groups, global tasks, contacts, email, messages, finance, work, health, browser sessions, or global facts.');
    staticParts.push('- Calendar reads and writes must use only the Family calendar tools. Event deletion always uses family_request_event_delete followed by family_confirm_event_delete from the same requester in this chat.');
    staticParts.push('- Family list items belong only in the local Family lists. Never describe them as Google Tasks or owner tasks.');
    staticParts.push('- Treat a concise household imperative, task/reminder capture, or unambiguous operational status as immediate Family-list input: "Apply to Lincoln school", "We need milk", "We\'re out of milk", "Pick up the dry cleaning", and "Remember to return the forms" require no confirmation, ID, list name, or rephrasing. A question such as "Got milk?" is a read/question, not a completion or list write.');
    staticParts.push('- Semantically route buying and household supplies to Groceries; pickups, drop-offs, and out-of-home actions to Errands; and other commitments to Family Tasks. An explicitly named live list always wins. Ask only when the destination is genuinely ambiguous.');
    staticParts.push('- Before editing, completing, reopening, archiving, or restoring a list item, call list_family_items and pass its exact ID, current text, and current list internally. The user never needs to say the ID. Resolve a natural name only when one row is the unique match; otherwise ask which one.');
    staticParts.push('- An exact open list item is idempotent: report that it is already there. Completed and archived rows are history, so a fresh request adds a new active row. Create a second active exact item only when the sender explicitly says another, one more, duplicate, or additional item.');
    staticParts.push('- Pass item text exactly from its message clause after removing only the action wrapper and explicit list cue. Never add extra words and never use the private create_task tool.');
    staticParts.push('- Include quantity, notes, due date, and assignee only when plainly supported by the source-bound intent (for example, "Add two gallons of milk" or "pickup forms for Sam by Friday"). They do not need labels. Never invent a field or borrow it from an unrelated request.');
    staticParts.push('- Instacart may create an Instacart-hosted shopping-list or recipe page. It does not directly select a store, add final products to a cart, check out, or purchase; give the returned link to the user. Spotify is limited to search and playback.');
    staticParts.push('- For Family events, collect title, date, time, location, and notes across natural turns. Create as soon as title/date/time are complete: one start time defaults to one hour and explicit all-day wording creates an all-day event. Do not ask for confirmation. Invitation language means add to the shared Family calendar; keep named people in Family-safe notes and explain briefly that separate invitations are not sent.');
  } else {
    if (uniqueCallable.includes('create_task')) {
      staticParts.push(`All tasks created via create_task automatically sync to Google Tasks on ${profileCfg.owner.name}'s phone. There is no separate reminder system.`);
    }

    staticParts.push(`\n--- Tool Routing ---`);
    staticParts.push('- CHECK BEFORE CLAIMING IGNORANCE: before telling the user you don\'t have a note, fact, reminder, person, or task about something — OR when they ask "what do you have on X" / "what did I tell you about Y" / "what are you tracking" — call recall_memory("<subject>") (or omit the subject for an overview). It pulls everything across facts, people, tasks, and messages in one shot and sees data the context blocks below may have dropped. Never say "I don\'t have that" without calling it first.');
    staticParts.push('- Mentions of a meeting, event, "tomorrow", a day-of-week → list_events FIRST.');
    staticParts.push('- Mentions of a person by name → check the --- People Context --- and --- Relevant Knowledge --- blocks in the session context below first; if not there, call find_person("<name>") or facts_about("<name>"). Save durable info about people with note_about_person.');
    staticParts.push('- Anything the user "needs to do later" → create_task.');
    staticParts.push('- User defers a surfaced task ("snooze", "remind me later", "not now", "tomorrow", "Friday") → call snooze_task(id, <ISO>) IMMEDIATELY. Resolve the date from the Date lookup in the session context below ("3 days from now" → find TODAY + 3 rows), at 9am local time unless they say otherwise.');
    staticParts.push('- User cancels a surfaced task ("cancel", "skip", "drop it", "not doing X") → call cancel_task(id) IMMEDIATELY. Don\'t just acknowledge — the heartbeat will keep re-pinging until the DB is mutated.');
    staticParts.push('- The task #id is the surfaced number — pull it from the most recent heartbeat message in conversation history.');
    staticParts.push('- Atomic facts with a clear subject (person, project, deadline) → save_fact. Use fact_type "preference" / "decision" / "metric" for things that change over time (they supersede prior values).');
    staticParts.push('- Generic notes / state without a subject → remember.');
    staticParts.push('- End of a substantive conversation → memory_checkpoint.');
    staticParts.push('- Hit a real-world wall (login, phone call, signature) → assign_human_task.');

    staticParts.push(`\n--- Anticipate ---`);
    staticParts.push('After answering, briefly consider: is there anything worth remembering? Does this imply a follow-up task? Should this go on the calendar? If yes to any, do it before ending the turn — don\'t ask permission for low-stakes saves. Prefer save_fact over remember whenever you can name a subject (person, project, entity).');
  }

  // ── Dynamic suffix ────────────────────────────────────────────────────────

  // Live session block (the date table is the load-bearing piece — see getDateReference)
  dynamicParts.push(`\n--- Session ---`);
  dynamicParts.push(`Group: ${group.name}`);
  dynamicParts.push(`Sender: ${user.name} (${user.role})`);
  dynamicParts.push(getDateReference());
  dynamicParts.push(`Context: ${getSituationContext()}`);
  // Owner-only: never render the owner's whereabouts into a shared or warm-tone session.
  const whereabouts = !isSharedAudience && user.tone === 'direct' ? getWhereabouts() : '';
  if (whereabouts) dynamicParts.push(whereabouts);

  // Check-in replies. Check-ins number their items 1..5 (not task ids) and offer
  // "more"; a terse reply only makes sense against the message it answers.
  // Only when the message is plausibly an answer to it: check-in wording
  // ("done 2", "more", a bare number), or the check-in is the last thing the
  // bot said and is under 3 hours old. Attaching a morning check-in to every
  // short message all evening made "Skip" (about something else) ambiguous.
  if (!isSharedAudience && user.tone === 'direct' && userMessage && userMessage.trim().length <= 60) {
    const meta = getRecentCheckinMeta(12);
    const checkinWording = /^\s*(\d{1,2}\b|(done|snooze|skip|drop|cancel|keep|more|details?|expand|full)\b[^a-z]*\d|(more|details?|expand|full)\s*[.!?]?\s*$)/i.test(userMessage);
    const lastBot = getRecentMessagesWithMetadata(group.key, 6).filter((m) => m.role === 'assistant').at(-1);
    const lastBotAt = lastBot ? Date.parse(`${lastBot.created_at.replace(' ', 'T')}Z`) : 0;
    const checkinIsLatest = !!meta && meta.at > lastBotAt && Date.now() - meta.at < 3 * 3600_000;
    const checkin = meta && (checkinWording || checkinIsLatest) ? meta.text : null;
    const wantsMore = /^\s*(more|details?|expand|full)\b/i.test(userMessage);
    const details = wantsMore ? getRecentDetails() : null;
    if (checkin || details) {
      dynamicParts.push('\n--- Last check-in / alert you sent ---');
      if (checkin) dynamicParts.push(checkin);
      if (details) dynamicParts.push(`\nFull detail behind it (the owner said "more": give the useful parts, same short numbered style, no walls of text):\n${details.slice(0, 6000)}`);
      dynamicParts.push('Numbers like "done 2" or "snooze 3" refer to the numbered items above, not task ids: map them to the real task/item before acting.');
    }
  }
  const taskState = isSharedAudience ? '' : getTaskState();
  // Jobs paused on the owner (a code, a login, a choice), so a bare reply like
  // "482913" or "done" reaches the right job.
  if (user.tone === 'direct' && !isSharedAudience) {
    try { const w = waitingBlock(); if (w) dynamicParts.push(`\n${w}`); } catch { /* tracker unavailable */ }
  }
  if (taskState) dynamicParts.push(taskState);

  // Recent Memory (surfaces persistent state so memory isn't write-only)
  const memoryBlock = getRecentMemoryBlock(group.key);
  if (memoryBlock) {
    dynamicParts.push('\n--- Recent Memory ---');
    dynamicParts.push(memoryBlock);
  }

  // Retrieved knowledge: Learned Preferences (always) + Relevant Knowledge
  // (when there's an inbound user message). Shared ~2500 char budget. Uses the
  // caller's precomputed smart-retrieval block when supplied, else the heuristic.
  const retrieved = isFamily
    ? ''
    : precomputedRetrieval !== undefined
      ? precomputedRetrieval
      : getRetrievedBlocks(userMessage, group.key);
  if (retrieved) dynamicParts.push(retrieved);

  // Voice-memo nudge: a long voice rant is usually thinking-out-loud, not a question.
  // Default to fact extraction over a chatty reply.
  if (!isFamily && userMessage && userMessage.startsWith('[Voice message]:') && userMessage.length > 300) {
    dynamicParts.push(`\n--- Voice Memo Mode ---`);
    dynamicParts.push('This is a long voice memo — likely the user thinking out loud, not asking a direct question. Prioritize extracting durable facts via save_fact (decisions, commitments, new people, ideas worth remembering) over a chatty response. A short ack ("got it, saved X, Y, Z") is usually enough.');
  }

  return { staticPrefix: staticParts.join('\n'), dynamic: dynamicParts.join('\n') };
}

export function loadSystemPrompt(group: GroupConfig, user: User, userMessage?: string): string {
  const { staticPrefix, dynamic } = loadSystemBlocks(group, user, userMessage);
  return `${staticPrefix}\n${dynamic}`;
}
